# Generated by Django 4.2.7 on 2023-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_description', models.CharField(max_length=255)),
                ('event_image', models.ImageField(upload_to='events')),
                ('event_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
        ),
    ]
