# Generated by Django 4.2.7 on 2023-11-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=30)),
                ('person_mail', models.EmailField(max_length=254)),
                ('person_address', models.CharField(max_length=100)),
                ('person_number', models.CharField(max_length=15)),
                ('person_count', models.IntegerField()),
                ('booking_on', models.DateField(auto_now=True)),
                ('event_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.event')),
            ],
        ),
    ]
