# Generated by Django 4.2.7 on 2023-11-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('member_label', models.CharField(max_length=100)),
                ('member_image', models.ImageField(upload_to='team')),
                ('member_description', models.TextField()),
                ('member_playlist', models.TextField()),
            ],
        ),
    ]
