# Generated by Django 4.2.7 on 2023-11-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
